<?php
Translator::tlschema("faq");
popup_header("General Questions");
$c = translate_inline("Return to Contents");
rawoutput("<a href='petition.php?op=faq'>$c</a><hr>");
OutputClass::output("`n`n`c`bGeneral questions`b`c`n");
OutputClass::output("`^1. What is the purpose of this game?`n");
OutputClass::output("`@To get chicks.`n");
OutputClass::output("Seriously, though. The purpose is to slay the green dragon.`n`n");
OutputClass::output("`^2. How do I find the green dragon?`n");
OutputClass::output("`@You can't.`n");
OutputClass::output("Well, sort of.");
OutputClass::output("You can't find her until you've reached a certain level.");
OutputClass::output("When you're at that level, it will be immediately obvious.`n`n");
OutputClass::output("`^3. How do I increase my level?`n");
OutputClass::output("`@Send us money.`n");
OutputClass::output("No, don't send money - you increase your experience by fighting creatures in the forest.");
OutputClass::output("Once you've gotten enough experience, you can challenge your master in the village.`n`n");
OutputClass::output("Well, you can send us money if you want (see PayPal link).`n`n");
OutputClass::output("`^4. Why can't I beat my master?`n");
OutputClass::output("`@He's far too wily for the likes of you.`n");
OutputClass::output("Did you ask him if you have enough experience?`n");
OutputClass::output("Have you tried purchasing some armor or weapons in the village?`n`n");
OutputClass::output("`^5. I used up all my turns. How do I get more?`n");
OutputClass::output("`@Send money.`n");
OutputClass::output("No, put your wallet away.");
OutputClass::output("There *are* a few ways to get an extra turn or two, but by and large you just have to wait for tomorrow.");
OutputClass::output("When a new day comes you'll have more energy.`n");
OutputClass::output("Don't bother asking us what those few ways are - some things are fun to find on your own.`n`n");
OutputClass::output("`^6. When does a new day start?`n");
OutputClass::output("`@Right after the old one ends.`n`n");
OutputClass::output("`^7. Arghhh, you guys are killing me with your smart answers - can't you just give me a straight answer?`n");
OutputClass::output("`@Nope.`n");
OutputClass::output("Well, okay, new days correspond with the clock in the village (can also be viewed from other places).");
OutputClass::output("When the clock strikes midnight, expect a new day to begin.");
OutputClass::output("The number of times a clock in LotGD strikes midnight per calendar day may vary by server.");
OutputClass::output("Beta server has 4 play days per calendar day, main server at LotGD.net has 2.");
OutputClass::output("Other servers depend on the admin.`n");
OutputClass::output("This server has %s days per calendar day.`n`n", Settings::getsetting("daysperday", 2));
OutputClass::output("`^8. Something's gone wrong!!!  How do I let you know?`n");
OutputClass::output("`@Send money.");
OutputClass::output("Better yet, send a petition.");
OutputClass::output("A petition should not say 'this doesn't work' or 'I'm broken' or 'I can't log in' or 'yo.  Sup?'");
OutputClass::output("A petition *should* be very complete in describing *what* doesn't work.");
OutputClass::output("Please tell us what happened, what the error message is (copy and paste is your friend), when it occurred, and anything else that may be helpful.");
OutputClass::output("\"`#I'm broken`@\" is not helpful.");
OutputClass::output("\"`#There are salmon flying out of my monitor when I log in`@\" is much more descriptive as well as humorous, although there's not much we can do about it.");
OutputClass::output("In general, please be patient with these requests - many people play the game, and as long as the admin is swamped with 'yo - Sup?' petitions, it will take some time to sift through them.`n`n");
OutputClass::output("`^9. What if all I have to say is 'yo - sup?'?`n");
OutputClass::output("`@If you don't have something nice (or useful, or interesting, or creative that adds to the general revelry of the game) to say, don't say anything.`n");
OutputClass::output("But if you do want to converse with someone, send them an email through Ye Olde Post Office.`n`n");
OutputClass::output("`^10. How do I use emotes?`n");
OutputClass::output("`@Type :, ::, or /me before your text.`n`n");
OutputClass::output("`^11. What's an emote?`n");
OutputClass::output("`&Farmgirl AnObviousAnswer punches you in the gut.`n");
OutputClass::output("`@That's an emote.");
OutputClass::output("You can emote in the village if you want to do an action rather than simply speaking.`n`n");
OutputClass::output("`^12. How do you get colors in your name?`n");
OutputClass::output("`@Eat funny mushrooms.`n");
OutputClass::output("No, put that mushroom away, colors are given out by a site's admin for a variety of reasons -- for example it might signify that the character was integral to the beta-testing process - finding a bug, helping to create creatures, etc, or being married to the admin (*cough*Appleshiner*cough*).");
OutputClass::output("Check with your admins to find out how they grant colors.`n`n");
OutputClass::output("`^13. Sup dOOd, iz it cool 2 uz common IM wurds in the village? Cuz u no, it's faster. R u down wit that?`n");
OutputClass::output("`@NO, for the love of Pete, use full words and good grammar, PLEASE!");
OutputClass::output("These are not words: U, R, Ur, Cya, K, Kay, d00d, L8tr, sup, na and anything else like that!`n`n");
OutputClass::output("`^14. Does that Curious Looking Rock have a purpose?`n");
OutputClass::output("`@Of course it does! It confuses newbies!`n");
OutputClass::output("Seriously, a wise man once said, \"`#Good things come to those who wait.`@\"");
OutputClass::output("This should also be applied to the Rock.`n`n");
OutputClass::output("`^15. Wow, there are mounts AND familiars in the stables! Can I have one of each?`n");
OutputClass::output("`@(Oh for the love of... [we get this question a lot])`n");
OutputClass::output("No! Not! Nix! Nada! You can only have one creature at a time.");
OutputClass::output("Not two. Certainly not three. Four is right out. Five? You must be joking!");
OutputClass::output("Now all together now, HOW many companion creatures can you have at a time?`n`n");
OutputClass::output("`^16. Why not?`n");
OutputClass::output("`@Because we're big meanies. Actually, the game's code just doesn't allow for that right now.");
OutputClass::output("It might in the next version, then again it might not. Please stop asking!`n`n");
OutputClass::output("`^17. What's with the <CLAN> thingies before peoples' names?`n");
OutputClass::output("`#<`2CLAN`#> `&Clan Member ClanMember strikes you with the flat side of his weapon.`n");
OutputClass::output("`3\"`@You dare claim ignorance of my clan's famous deeds? I am `\$ClanMember`@, a member of the mighty clan CLAN, which is short for Completely Ludicrous And Nonsensical! We have performed many a deed after having planned it in the privacy of our `%Clan Hall`@.");
OutputClass::output("Our leaders and officers are among the mightiest in the land. Bolstered by the support of our friends and clanmates, we prevail!`3\"`n`n");
OutputClass::output("`^18. I am so confused! What is going on in the village square/Garden/Inn/etc.?`n");
OutputClass::output("`@A hubbub.`n");
OutputClass::output("The fact is that because there's so many people, there can be several conversations happening at once in any given area.");
OutputClass::output("Also, the thing to understand is that not all the comments are posted immediately, and that sometimes a person won't press the refresh or add button for several minutes, during which time more comments could have been said that the person missed while they were typing their own.");
OutputClass::output("Not to worry, though. Don't be shy, join in!`n`n");
rawoutput("<hr><a href='petition.php?op=faq'>$c</a>");
?>